node {
  stage('SCM') {
    checkout scm
  }
  stage('SonarQube Analysis') {
    def mvn = tool 'TaskSeven';
    withSonarQubeEnv() {
      sh "${mvn}/bin/mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Group-Two-AOOP_Task-07_TaskSeven_a82c5535-18b7-4ea4-9d6f-a5f0771c34d4 -Dsonar.projectName='TaskSeven'"
    }
  }
}
