pipeline {
    agent any

    tools {
        jdk 'JDK17'
        maven 'Maven-3'
    }

    stages {
        stage('Build') {
            steps {
                dir('TaskSeven') {
                    bat 'mvn clean install'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('TaskSeven') {
                    withSonarQubeEnv('SonarQube') {
                        bat 'mvn sonar:sonar'
                    }
                }
            }
        }
    }
}
